### ISSUE TITLE
Problem under Fritz

### ISSUE THREAD

**Issue by SzotsGabor** [amanjpro/zahak#102] opened 2021-08-11 08:25 UTC
When Zahak is started from the command line it displays a lot of characters probably intended to show its name. I guess that may be responsible for the engine exiting under Fritz every time with some exception.
I'm not sure because this occurs only when playing engine tournaments, it did not occur when I myself played against Zahak. Could be some UCI implementation issue, e.g. wrong order of commands at start time.

**Comment by tissatussa** [comment] 2021-08-11 10:42
by "a lot of characters" you probably mean the starting logo in text art .. i don't think that's the cause but you could be right .. i guess this appears on Windows but i use Linux and i can not use Fritz .. you write "exiting under Fritz every time with some exception" : does it exit immediately with a certain exception, or suddenly during a game ? That's not clear to me .. you could test [SugaR](https://github.com/Zerbinati/SugaR-AI), it also has a large header after execution :

![sugar_uci](https://user-images.githubusercontent.com/1109281/129015511-982cf32b-8e00-47f1-a65a-b4396aaefd8a.png)

now the engine is ready to receive the first "uci" command.
NOTE: many engines show no output (header) after execution ..

**Comment by SzotsGabor** [comment] 2021-08-11 13:57
> by "a lot of characters" you probably mean the starting logo in text art .. i don't think that's the cause but you could be right .. i guess this appears on Windows but i use Linux and i can not use Fritz .. you write "exiting under Fritz every time with some exception" : does it exit immediately with a certain exception, or suddenly during a game ? That's not clear to me .. you could test [SugaR](https://github.com/Zerbinati/SugaR-AI), it also has a large header after execution :
> 
> ![sugar_uci](https://user-images.githubusercontent.com/1109281/129015511-982cf32b-8e00-47f1-a65a-b4396aaefd8a.png)
> 
> now the engine is ready to receive the first "uci" command.
> NOTE: many engines show no output (header) after execution ..



> 
> 
> by "a lot of characters" you probably mean the starting logo in text art .. i don't think that's the cause but you could be right .. i guess this appears on Windows but i use Linux and i can not use Fritz .. you write "exiting under Fritz every time with some exception" : does it exit immediately with a certain exception, or suddenly during a game ? That's not clear to me .. you could test [SugaR](https://github.com/Zerbinati/SugaR-AI), it also has a large header after execution :
> 

It seems to me that Zahak exits immediately after leaving the external book. Or 1 or 2 moves later, I was not able to detect. The game is recorded as if it were not played.
I do not test SugaR, SF derivatives do not interest me. Anyway, to try if there is a problem with it I would have to include it in a tournament, for which I have no time and resources.

**Comment by amanjpro** [comment] 2021-08-11 14:47
Hey Gabor,

Thanks for your report, I am on Ubuntu, and I cannot run Fritz, but I think I might know what is the problem. Probably Fritz never sends "ucinewgame" or "position startpos", and it starts with "position startpos moves ...", and upto version 5.0, this made Zahak to fail:

```
stop
position startpos moves e2e4
go infinite
info depth 1 seldepth 1 tbhits 0 hashfull 0 nodes 49 nps 332485 score cp 0 time 0 pv b8a6
info depth 2 seldepth 1 tbhits 16 hashfull 0 nodes 70 nps 289257 score cp 0 time 0 pv b8a6
info depth 3 seldepth 1 tbhits 32 hashfull 0 nodes 91 nps 295675 score cp 0 time 0 pv b8a6
info depth 4 seldepth 1 tbhits 48 hashfull 0 nodes 112 nps 301929 score cp 0 time 0 pv b8a6
info depth 5 seldepth 1 tbhits 64 hashfull 0 nodes 133 nps 307065 score cp 0 time 0 pv b8a6
info depth 6 seldepth 1 tbhits 80 hashfull 0 nodes 154 nps 310985 score cp 0 time 0 pv b8a6
info depth 7 seldepth 1 tbhits 96 hashfull 0 nodes 175 nps 287345 score cp 0 time 0 pv b8a6
info depth 8 seldepth 1 tbhits 112 hashfull 0 nodes 196 nps 291196 score cp 0 time 0 pv b8a6
info depth 9 seldepth 1 tbhits 128 hashfull 0 nodes 217 nps 294917 score cp 0 time 0 pv b8a6
info depth 10 seldepth 1 tbhits 144 hashfull 0 nodes 238 nps 298201 score cp 0 time 0 pv b8a6
info depth 11 seldepth 1 tbhits 160 hashfull 0 nodes 259 nps 291944 score cp 0 time 0 pv b8a6
info depth 12 seldepth 1 tbhits 176 hashfull 0 nodes 280 nps 294000 score cp 0 time 0 pv b8a6
info depth 13 seldepth 1 tbhits 192 hashfull 0 nodes 301 nps 292883 score cp 0 time 1 pv b8a6
info depth 14 seldepth 1 tbhits 208 hashfull 0 nodes 322 nps 294765 score cp 0 time 1 pv b8a6
info depth 15 seldepth 1 tbhits 224 hashfull 0 nodes 343 nps 296981 score cp 0 time 1 pv b8a6
info depth 16 seldepth 1 tbhits 240 hashfull 0 nodes 364 nps 299050 score cp 0 time 1 pv b8a6
info depth 17 seldepth 1 tbhits 256 hashfull 0 nodes 385 nps 301016 score cp 0 time 1 pv b8a6
info depth 18 seldepth 1 tbhits 272 hashfull 0 nodes 406 nps 302817 score cp 0 time 1 pv b8a6
info depth 19 seldepth 1 tbhits 288 hashfull 0 nodes 427 nps 304410 score cp 0 time 1 pv b8a6
info depth 20 seldepth 1 tbhits 304 hashfull 0 nodes 448 nps 305877 score cp 0 time 1 pv b8a6
info depth 21 seldepth 1 tbhits 320 hashfull 0 nodes 469 nps 307171 score cp 0 time 1 pv b8a6
info depth 22 seldepth 1 tbhits 336 hashfull 0 nodes 490 nps 305467 score cp 0 time 1 pv b8a6
info depth 23 seldepth 1 tbhits 352 hashfull 0 nodes 511 nps 305330 score cp 0 time 1 pv b8a6
info depth 24 seldepth 1 tbhits 368 hashfull 0 nodes 532 nps 300686 score cp 0 time 1 pv b8a6
info depth 25 seldepth 1 tbhits 384 hashfull 0 nodes 553 nps 295000 score cp 0 time 1 pv b8a6
info depth 26 seldepth 1 tbhits 400 hashfull 0 nodes 574 nps 288399 score cp 0 time 1 pv b8a6
info depth 27 seldepth 1 tbhits 416 hashfull 0 nodes 595 nps 283637 score cp 0 time 2 pv b8a6
info depth 28 seldepth 1 tbhits 432 hashfull 0 nodes 616 nps 282044 score cp 0 time 2 pv b8a6
info depth 29 seldepth 1 tbhits 448 hashfull 0 nodes 637 nps 279002 score cp 0 time 2 pv b8a6
info depth 30 seldepth 1 tbhits 464 hashfull 0 nodes 658 nps 282821 score cp 0 time 2 pv b8a6
info depth 31 seldepth 1 tbhits 480 hashfull 0 nodes 679 nps 285614 score cp 0 time 2 pv b8a6
info depth 32 seldepth 1 tbhits 496 hashfull 0 nodes 700 nps 287141 score cp 0 time 2 pv b8a6
info depth 33 seldepth 1 tbhits 512 hashfull 0 nodes 721 nps 288395 score cp 0 time 2 pv b8a6
info depth 34 seldepth 1 tbhits 528 hashfull 0 nodes 742 nps 290489 score cp 0 time 2 pv b8a6
info depth 35 seldepth 1 tbhits 544 hashfull 0 nodes 763 nps 292988 score cp 0 time 2 pv b8a6
info depth 36 seldepth 1 tbhits 560 hashfull 0 nodes 784 nps 295473 score cp 0 time 2 pv b8a6
info depth 37 seldepth 1 tbhits 576 hashfull 0 nodes 805 nps 298453 score cp 0 time 2 pv b8a6
info depth 38 seldepth 1 tbhits 592 hashfull 0 nodes 826 nps 301831 score cp 0 time 2 pv b8a6
info depth 39 seldepth 1 tbhits 608 hashfull 0 nodes 847 nps 303513 score cp 0 time 2 pv b8a6
info depth 39 seldepth 1 tbhits 608 hashfull 0 nodes 847 nps 302080 score cp 0 time 2 pv b8a6
bestmove b8a6
```

But, the upcoming version will fix that:

```
position startpos moves e2e4
go infinite
info depth 1 seldepth 1 hashfull 0 nodes 53 nps 163782 score cp -5 time 0 pv e7e5
info depth 2 seldepth 2 hashfull 0 nodes 406 nps 220680 score cp -52 time 1 pv g8f6 b1c3
info depth 3 seldepth 3 hashfull 0 nodes 1646 nps 352038 score cp -4 time 4 pv g8f6 e4e5 f6e4
info depth 4 seldepth 4 hashfull 0 nodes 2250 nps 385537 score cp -52 time 5 pv b8c6 d2d4 e7e5 c2c3
info depth 5 seldepth 5 hashfull 0 nodes 3463 nps 441630 score cp -12 time 7 pv d7d5 e4d5 c7c6 d2d4 c6d5
info depth 6 seldepth 6 hashfull 0 nodes 6047 nps 513797 score cp -11 time 11 pv g8f6 b1c3 d7d5 e4d5 c7c6 d2d4
info depth 7 seldepth 7 hashfull 0 nodes 10820 nps 587081 score cp -13 time 18 pv d7d5 e4d5 c7c6 g1f3 e7e6 d2d4 e6d5
info depth 8 seldepth 8 hashfull 0 nodes 23394 nps 691120 score cp -27 time 33 pv e7e5 g1f3 d7d5 f3e5 d5e4 d2d4 b8c6 e5c6
info depth 9 seldepth 9 hashfull 0 nodes 33881 nps 733580 score cp -27 time 46 pv e7e5 g1f3 d7d5 f3e5 d5e4 d2d4 b8c6 e5c6 b7c6
info depth 10 seldepth 10 hashfull 1 nodes 72025 nps 814544 score cp -14 time 88 pv d7d5 e4d5 c7c6 d2d4 c6d5 b1c3 b8c6 g1f3 g8f6 c1e3
info depth 11 seldepth 11 hashfull 1 nodes 104344 nps 883891 score cp -10 time 118 pv d7d5 e4d5 c7c6 d2d4 c6d5 c1f4 b8c6 g1f3 g8f6 b1c3 e7e6
info depth 12 seldepth 12 hashfull 2 nodes 168861 nps 966794 score cp -20 time 174 pv d7d5 e4d5 c7c6 d2d4 c6d5 c1f4 b8c6 g1f3 g8f6 b1c3 c8f5 f1e2
info depth 13 seldepth 14 hashfull 6 nodes 398591 nps 1092750 score cp -28 time 364 pv e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 d7d5 d4c6 b7c6 e4d5 g8e7 d5c6 d8d1 e1d1
info depth 14 seldepth 14 hashfull 8 nodes 543798 nps 1133392 score cp -26 time 479 pv e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 d7d5 b1c3 g8f6 e4d5 f6d5 d4c6 b7c6 f1c4
info depth 15 seldepth 15 hashfull 12 nodes 865995 nps 1201093 score cp -25 time 721 pv e7e5 g1f3 g8f6 b1c3 b8c6 d2d4 e5d4 f3d4 f8c5 d4c6 b7c6 f1c4 d8e7 e1g1 f6e4
quit
```

Can you test this binary for me, and see if it fixes it (this is not meant for CCRL testing, just to make sure my hunch is correct):
https://gofile.io/d/SrZZT2

**Comment by SzotsGabor** [comment] 2021-08-11 15:21
Hi Amanj,

It seems you have solved the problem. Could you please compile a version for me which is totally identical with Zahak 5.0 but with the Fritz fix? I see the one you linked to has more than that, e.g. multicore.

**Comment by amanjpro** [comment] 2021-08-11 15:31
Yes the version I sent you is considerably stronger than 5.0.

I will see if I can easily backport the fix to version 5.0 for you, the only issue it is going to keep the hash table entries between games. Which probably gives Zahak an unfair advantage. I usually expect to either receive `ucinewgame` or `position startpos` between games, else keep hash entries

**Comment by SzotsGabor** [comment] 2021-08-11 15:40
> 
> 
> Yes the version I sent you is considerably stronger than 5.0.
> 
> I will see if I can easily backport the fix to version 5.0 for you, the only issue it is going to keep the hash table entries between games. Which probably gives Zahak an unfair advantage. I usually expect to either receive `ucinewgame` or `position startpos` between games, else keep hash entries

Why does it matter if hash entries from an other game are kept?

Anyway, this is a minor issue for me (some Nalwald - Zahak games will not be played), so no pressure.

**Comment by amanjpro** [comment] 2021-08-11 15:40
Wait, don't download the above link, download the one I send you next. The above was a wrong upload

**Comment by amanjpro** [comment] 2021-08-11 15:41
Revised link: https://gofile.io/d/PlkoF4

**Comment by amanjpro** [comment] 2021-08-11 15:42
> > Yes the version I sent you is considerably stronger than 5.0.
> > I will see if I can easily backport the fix to version 5.0 for you, the only issue it is going to keep the hash table entries between games. Which probably gives Zahak an unfair advantage. I usually expect to either receive `ucinewgame` or `position startpos` between games, else keep hash entries
> 
> Why does it matter if hash entries from an other game are kept?
> 
> Anyway, this is a minor issue for me (some Nalwald - Zahak games will not be played), so no pressure.

It only matters, because that means somehow the engines will learn from their previous games, by reusing the same hash table... but I could be completely wrong, and this is not even an issue

**Comment by SzotsGabor** [comment] 2021-08-11 15:45
Fixed version is happily playing under Fritz. Thank you Amanj.

**Comment by amanjpro** [comment] 2021-08-11 15:48
Thanks again for testing it :)

I am closing this issue, as it is addressed :)

**Closed by amanjpro** 2021-08-11 15:48 UTC
